### ISSUE TITLE
What steps did you take to compile the XMRig Binary for android?

### ISSUE THREAD

**Issue by 0xPiyush** [upost/MoneroMiner#6]
Hi I tried to compile latest release of XMRig for android but it kept giving me segmentation faults, would you mind guiding on how to compile the latest release of XMRig as the binaries in the project have been deprecated.
Thanks.

**Comment by Saikatsaha1996** [comment]
Fast Install termux
After that
1) pkg upgrade -y
2) pkg install git cmake libuv clang nano -y
3) git clone --single-branch https://github.com/xmrig/xmrig.git
4) git clone https://github.com/xmrig/xmrig-amd.git
5) cd xmrig
6) mkdir build && cd build
7) cmake .. -DWITH_HTTPD=OFF -DWITH_TLS=OFF -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_HWLOC=OFF -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 
9) ls
10) make 
11) cp ../src/config.json config.json
12) nano config.json

11) donate.v2.xmrig.com:3333
12) xmr.pool.minergate.com:45700
13) CONTROL+\ ,donate.v2.xmrig.com:3333, replace with ( your pool address ) , y enter
14) Control +\ , and past   YOUR_WALLET_ADDRESS , replace with ( your user name or wallet address) , y enter, and scroll down and check your all details.. 
15) control + x 
16) y enter
17) enter
18) ./xmrig-notls
19) enjoy...!
